### ISSUE TITLE
Merge Main openIMIS initiative to forked EHIS repo openimis-be_py

### ISSUE THREAD

**Issue by mngoe** [Ethiopian-Health-Insurance-Service/openimis-be_py#1]
Currently Forked version of openIMIS in your repo is not merged with last version of openIMIS.
You should have the same main version and be sure that your main use the same last tag official release (24.04)

**Comment by mngoe** [comment]
@Lishaneticha You seems right on your commit, this import will probably create an error as this module is not present in the 24.04 version.

PR created : https://github.com/openimis/openimis-be_py/pull/279
Community will probably merge or revert.

**Comment by Lishaneticha** [comment]
@mngoe, awesome 👍

**Comment by mngoe** [comment]
@Lishaneticha Please follow github Workflow as discussed.
Basically you should have at least those branches : 
- develop-ethiopia
- test-ethiopia
- main-ethiopia

(At this stage all thoses branches should comes from the release/24.04)

All modules forked should use this structure. 
And new features should have specific branch (features-xxx) we will PR to the correct branch.

**Comment by Lishaneticha** [comment]
@mngoe this is good. Thanks for the update 🙏
